name: Linux Packages

on:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:
    # cargo-dist exposes the plan from the plan step, as a JSON string,
    # to your job if it needs it
    inputs:
      plan:
        required: true
        type: string

jobs:
  greeter:
    runs-on: ubuntu-latest
    # This is optional; it exposes the plan to your job as an environment variable
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - uses: actions/checkout@v4
      # Fetch artifacts from scratch-storage
      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*-linux-gnu
          path: target/distrib/
          merge-multiple: true
      - name: Create archive
        run: |
          VERSION="$(echo "$PLAN" | jq --compact-output '.releases | first | .app_version')"
          tar -xvf target/distrib/scope-x86_64-unknown-linux-gnu.tar.xz -C target
          tar -xvf target/distrib/scope-aarch64-unknown-linux-gnu.tar.xz -C target
          .github/bin/create-packages-linux.sh ${VERSION}
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux-pkgs
          path: |
            target/upload/scope-*-1.aarch64.rpm
            target/upload/scope-*-1.aarch64.rpm.sha256
            target/upload/scope-*-1.x86_64.rpm
            target/upload/scope-*-1.x86_64.rpm.sha256
            target/upload/scope_*_amd64.deb
            target/upload/scope_*_amd64.deb.sha256
            target/upload/scope_*_arm64.deb
            target/upload/scope_*_arm64.deb.sha256
          if-no-files-found: error
